---
###every yaml start with three dash
- 
  #target where our play is going to run 
  hosts: client

  vars:
    tomcat_download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.68/bin/apache-tomcat-9.0.68.tar.gz
    tomcat_download_location: /usr/share/tomcat/apache-tomcat-9.0.68.tar.gz
  ##define list of task that we are executing

  tasks:
    - name: update my endpoint and install openjdk
      ansible.builtin.apt:
        name: default-jdk
        state: latest
        update_cache: yes
    - name: add group tomcat 
      ansible.builtin.group:
        name: tomcat 
        state: present ###absent
    - name: add user tomcat 
      ansible.builtin.user:
        name: tomcat 
        group: tomcat 
    - name: create a tomcat directory 
      ansible.builtin.file:
         path: /usr/share/tomcat
         state: directory
         owner: tomcat 
         group: tomcat 
    - name: Download Tomcat 
      ansible.builtin.get_url:
        url: "{{tomcat_download_url}}"
        dest: "{{tomcat_download_location}}"  
    - name: unarvhice the tomcat 
      ansible.builtin.unarchive:
        src: "{{tomcat_download_location}}" 
        dest: /usr/share/tomcat 
        remote_src: yes #give this tar zxvf name 
        extra_opts: [--strip-components=1]
        owner: tomcat 
        group: tomcat 
        creates: /usr/share/tomcat/bin
    - name: copy the tomcat service 
      template:
        src: templates/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service 
      when: ansible_service_mgr == 'systemd'
    - name: start and enadle tomcat 
      service:
        daemon_reload: yes 
        name: tomcat 
        state: started
        enabled: yes 
      when: ansible_service_mgr == 'systemd'